server:
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "ahmadraihan123" 
  dbname: "postgres"            
jwt:
  secret: "kunci_rahasia_yang_sangat_aman"

users:
  - username: "user1"
    password: "password123"